### ISSUE TITLE
Is it recognized as a string type unconditionally when importing json_extract data?

### ISSUE THREAD

**Issue by lazychase** [boostorg/mysql#128] opened 2023-03-16 23:54 UTC
Let's say I have a json column like this:

> {
>    "strValue":"apple",
>    "numberValue":1220
> }

If I do a query like this

> SELECT 
>  JSON_EXTRACT(myField, '$.strValue') 
> , JSON_EXTRACT(myField, '$.numberValue') 

When I try to read the numeric value, it recognizes the type as string type.

> row[1].as_int64()

> BOOST_CXX14_CONSTEXPR std::int64_t boost::mysql::field_view::as_int64() const
> {
>     if (is_field_ptr())
>         return repr_.field_ptr->as<std::int64_t>();
>     check_kind(internal_kind::int64);  // ---> It is confirmed as string type.
>     return repr_.int64;
> }
>

**Comment by lazychase** [comment] 2023-03-17 00:16
Additionally, if I didn't add an alias to the field, I couldn't read the value properly.

> SELECT
> JSON_EXTRACT(myField, '$.strValue') as a
> , JSON_EXTRACT(myField, '$.numberValue') as b


To recap, I have two questions.
1. json-related types are unconditionally returned as string types.
2. When querying the json type, you must attach an alias for it to work.

**Comment by lazychase** [comment] 2023-03-17 01:43
I also needed to be careful when attaching a nickname.

When I search both non-json fields and json fields at the same time, even if I attach an alias only to the json field, I couldn't get the value properly.

> SELECT not_json_field, json_field as a  ==> The value of json_field is not retrieved properly.
> SELECT not_json_field as a, json_field as b  ==> In this way, all aliases must be attached to properly retrieve values.

**Comment by anarthal** [comment] 2023-03-19 18:19
Hi @lazychase,

First of all, which version of MySQL/MariaDB are you using? JSON differs greatly between MySQL and MariaDB.

Question 1: when you do `SELECT JSON_EXTRACT(myField, '$.numberValue')`, the type of the generated field is still JSON, as given by `boost::mysql::column_type::json`. Fields with a JSON type are always represented as strings in `field` and `field_view`, since they main contain any arbitrary JSON value. This is documented [in this table](https://www.boost.org/doc/libs/master/libs/mysql/doc/html/mysql/fields.html#mysql.fields.mysql_to_c_type_mappings).

If you're completely sure that `JSON_EXTRACT(myField, '$.numberValue')` always yields an integer value for your schema, then I suggest you to modify your query to `SELECT CAST(JSON_EXTRACT(f1, '$.numberValue') AS SIGNED)`, which will cause MySQL to cast the extracted value to an integer, so that you can call `field_view::as_int64()` on it.

Question 2: I can't reproduce. I need more information - what does "I couldn't read the value properly" mean? Which functions are you calling, and what behavior are you observing (exception, crash...)?

Regards,
Ruben.

**Comment by chaseYLC** [comment] 2023-03-22 00:50
* MySQL Version : 8.0.31
* Boost Version : 1.80
* Boost MySQL : 0.2.0

It means that no exception or crash occurred, and the expected value was not returned.

I have data like this:
> === table schema ===
> CREATE TABLE `sample` (
> 	`numValue` INT(10) NOT NULL DEFAULT '1',
> 	`jsonValue` JSON NOT NULL
> );
> === table data ===
> numValue : 10
> jsonValue: "{"key":"anyValue"}"
> 

When i do these code it returns empty string.
> SELECT numValue , jsonValue as a FROM sample where numValue=10;
> assert( boost::mysql::row[1].as_string() == "" );


When I gave all fields an alias, it returned as expected.
> SELECT numValue as a , jsonValue as b FROM sample where numValue=10;
> assert( boost::mysql::row[1].as_string() == "{"key":"anyValue"}" );

**Comment by chaseYLC** [comment] 2023-03-22 01:35
>  suggest you to modify your query to SELECT CAST(JSON_EXTRACT(f1, '$.numberValue') AS SIGNED), which will cause MySQL to cast the extracted value to an integer, so that you can call field_view::as_int64() on it

thanks. this was helpful to me.


about Question 2>> When I did not specify an alias for all return items, there was a phenomenon that the json field value returned an empty string. This seems to be the result of my poor stack management.

I am using boost-json library, predefined BOOST_JSON_STACK_BUFFER_SIZE is 4096, The problem seems to have arisen as the value of the json field I manage is very large.

**Comment by anarthal** [comment] 2023-03-22 16:30
Cool. If this solved both of your questions, I will close the issue. Thanks for using the library.

**Closed by anarthal** 2023-03-22 16:30 UTC
